#!/bin/bash
# ============================================================
# RT Connect — Full Ubuntu 22.04 Installation Script
# Run as root: sudo bash install.sh
# ============================================================
set -e

APP_DIR="/opt/rtconnect"
BACKEND_DIR="$APP_DIR/backend"
FRONTEND_DIR="$APP_DIR/frontend"
SERVICE_USER="rtconnect"
DB_NAME="rtzkconnect_db"
DB_USER="rtconnect"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Check root ─────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "Run this script as root: sudo bash install.sh"

# ── Prompt for configuration ────────────────────────────────
echo ""
echo "========================================"
echo "  RT Connect — Deployment Configuration"
echo "========================================"
echo ""
read -p "Server IP or domain (e.g. 192.168.1.100): " SERVER_HOST
read -s -p "PostgreSQL password for '$DB_USER' (choose a strong one): " DB_PASSWORD
echo ""
read -s -p "Confirm password: " DB_PASSWORD_CONFIRM
echo ""
[[ "$DB_PASSWORD" != "$DB_PASSWORD_CONFIRM" ]] && error "Passwords do not match"
read -p "Restore database from dump? [y/N]: " RESTORE_DB
echo ""

# ── System update ───────────────────────────────────────────
info "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq

# ── Install system dependencies ─────────────────────────────
info "Installing system dependencies..."
apt-get install -y -qq \
    python3.11 python3.11-venv python3.11-dev python3-pip \
    postgresql postgresql-contrib \
    nginx \
    curl wget git \
    libpq-dev build-essential \
    ufw fail2ban

# ── Create service user ─────────────────────────────────────
info "Creating service user '$SERVICE_USER'..."
if ! id "$SERVICE_USER" &>/dev/null; then
    useradd --system --shell /bin/bash --home "$APP_DIR" --create-home "$SERVICE_USER"
fi

# ── Create app directories ──────────────────────────────────
info "Creating application directories..."
mkdir -p "$BACKEND_DIR" "$FRONTEND_DIR"
mkdir -p "$APP_DIR/logs" "$APP_DIR/backups"

# ── Copy application files ──────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"

info "Copying backend files..."
rsync -a --exclude='__pycache__' --exclude='*.pyc' --exclude='.pytest_cache' \
    --exclude='venv' --exclude='*.log' --exclude='*.db' \
    "$PACKAGE_DIR/backend/" "$BACKEND_DIR/"

info "Copying frontend files..."
rsync -a "$PACKAGE_DIR/frontend/" "$FRONTEND_DIR/"

# ── Python virtual environment ──────────────────────────────
info "Setting up Python virtual environment..."
python3.11 -m venv "$BACKEND_DIR/venv"
"$BACKEND_DIR/venv/bin/pip" install --upgrade pip -q
"$BACKEND_DIR/venv/bin/pip" install -r "$BACKEND_DIR/requirements.txt" -q
info "Python dependencies installed"

# ── PostgreSQL setup ────────────────────────────────────────
info "Configuring PostgreSQL..."
systemctl enable postgresql --now

# Create DB user and database
sudo -u postgres psql <<EOF
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_USER') THEN
    CREATE USER $DB_USER WITH ENCRYPTED PASSWORD '$DB_PASSWORD';
  ELSE
    ALTER USER $DB_USER WITH ENCRYPTED PASSWORD '$DB_PASSWORD';
  END IF;
END
\$\$;
CREATE DATABASE $DB_NAME OWNER $DB_USER 2>/dev/null || true;
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
EOF

info "PostgreSQL: database '$DB_NAME' and user '$DB_USER' ready"

# ── Restore database dump ───────────────────────────────────
if [[ "$RESTORE_DB" =~ ^[Yy]$ ]]; then
    DUMP_FILE="$PACKAGE_DIR/db_dump.sql"
    if [[ -f "$DUMP_FILE" ]]; then
        info "Restoring database from dump..."
        PGPASSWORD="$DB_PASSWORD" psql -U "$DB_USER" -d "$DB_NAME" -f "$DUMP_FILE"
        info "Database restored successfully"
    else
        warn "db_dump.sql not found — database will be initialized empty on first start"
    fi
fi

# ── Write production .env ───────────────────────────────────
info "Writing production environment file..."
cat > "$BACKEND_DIR/.env" <<EOF
# RT Connect Production Environment
# Generated by install.sh on $(date)

# Database
DB_HOST=localhost
DB_PORT=5432
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME

# API
API_HOST=0.0.0.0
API_PORT=8000
API_VERSION=2.0.0

# CORS — allow the Nginx frontend origin
ALLOWED_ORIGINS=http://$SERVER_HOST,https://$SERVER_HOST

# ZKTeco device defaults (update per device in the web UI)
DEVICE_IP=127.0.0.1
DEVICE_PORT=4370
DEVICE_TIMEOUT=30
DEVICE_PASSWORD=0
EOF
chmod 600 "$BACKEND_DIR/.env"

# ── Install systemd service ─────────────────────────────────
info "Installing systemd service..."
cp "$SCRIPT_DIR/rtconnect-api.service" /etc/systemd/system/rtconnect-api.service
# Patch paths and user into service file
sed -i "s|__APP_DIR__|$APP_DIR|g" /etc/systemd/system/rtconnect-api.service
sed -i "s|__SERVICE_USER__|$SERVICE_USER|g" /etc/systemd/system/rtconnect-api.service
systemctl daemon-reload
systemctl enable rtconnect-api

# ── Nginx configuration ─────────────────────────────────────
info "Configuring Nginx..."
cp "$SCRIPT_DIR/nginx.conf" /etc/nginx/sites-available/rtconnect
sed -i "s|__SERVER_HOST__|$SERVER_HOST|g" /etc/nginx/sites-available/rtconnect
sed -i "s|__FRONTEND_DIR__|$FRONTEND_DIR|g" /etc/nginx/sites-available/rtconnect
ln -sf /etc/nginx/sites-available/rtconnect /etc/nginx/sites-enabled/rtconnect
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl enable nginx --now

# ── Set file permissions ────────────────────────────────────
info "Setting file permissions..."
chown -R "$SERVICE_USER:$SERVICE_USER" "$APP_DIR"
chmod -R 755 "$APP_DIR"
chmod 600 "$BACKEND_DIR/.env"

# ── Firewall ────────────────────────────────────────────────
info "Configuring firewall..."
ufw --force enable
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw status

# ── Start services ──────────────────────────────────────────
info "Starting services..."
systemctl restart rtconnect-api
systemctl restart nginx

# ── Verify ─────────────────────────────────────────────────
sleep 3
if systemctl is-active --quiet rtconnect-api; then
    info "rtconnect-api service is running"
else
    error "rtconnect-api failed to start. Check: journalctl -u rtconnect-api -n 50"
fi

if systemctl is-active --quiet nginx; then
    info "Nginx is running"
fi

echo ""
echo "========================================"
echo -e "${GREEN}  RT Connect deployed successfully!${NC}"
echo "========================================"
echo ""
echo "  Frontend : http://$SERVER_HOST"
echo "  API docs : http://$SERVER_HOST/api/docs"
echo "  Logs     : journalctl -u rtconnect-api -f"
echo "  Backup   : sudo bash $SCRIPT_DIR/backup_db.sh"
echo ""
echo "  Default login: admin / admin123"
echo "  CHANGE THE PASSWORD after first login!"
echo ""
